name: Extract Source Code
run-name: Update Source Code to ${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. 3.0.0)'
        required: true
        type: string

concurrency:
  group: update
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Tool Repo
        uses: actions/checkout@v3
        with:
          path: tools
      - name: Checkout Source Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPO_PATH }}
          token: ${{ secrets.PAT_TOKEN }}
          path: github
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Fetch & Extract Code
        run: |
          echo "::group::Update apt"
          sudo apt update
          sudo apt install curl -y
          sudo apt autoremove -y
          sudo apt autoclean
          echo "::endgroup::"
          cd tools
          chmod +x extract.sh
          sudo ./extract.sh ${{ github.event.inputs.version }}
      - name: Commit Changes
        run: |
          cd github
          sudo rm -rf ./*
          sudo mv ../tools/github-v${{ github.event.inputs.version }}/* .
          sudo chmod -R 777 .
          git config user.name actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "GitHub Enterprise Server v${{ github.event.inputs.version }}"
          git tag -a v${{ github.event.inputs.version }} -m "GitHub Enterprise Server v${{ github.event.inputs.version }}"
          git push origin master
          git push origin v${{ github.event.inputs.version }}
